name: Deploy CloudRegistry

on:
  push:
    branches:
      - main  # Scatta ogni volta che fai push sul ramo main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
    # 1. Scarica il codice dal tuo repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Installa Terraform nel server di GitHub
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 3. Crea lo ZIP del codice Python (come facevi a mano)
    - name: Zip Backend Code
      run: |
        zip codice.zip index.py

    # 4. Inizializza Terraform
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Se usi AWS Academy aggiungi: AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: |
        cd infra
        terraform init

    # 5. Applica le modifiche su AWS
    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Se usi AWS Academy aggiungi: AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: |
        cd infra
        terraform apply -auto-approve