name: Deploy CloudRegistry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # MANIERE FORTI: Cancelliamo qualsiasi residuo locale che confonde Terraform
    - name: Clean Old State
      run: |
        rm -rf .terraform
        rm -f terraform.tfstate
        rm -f terraform.tfstate.backup

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Zip Backend Code
      run: |
        zip codice.zip index.py

    # Init pulito che punta a S3 senza chiedere nulla
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init -input=false

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform apply -auto-approve -input=false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1  # <--- QUESTO È QUELLO CHE MANCAVA!

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: registro-note-app
        IMAGE_TAG: latest
      run: |
        # Entriamo nella cartella del backend note
        cd backend
        # Costruiamo l'immagine
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Spediamo l'immagine su AWS
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Force ECS Update
      run: |
        aws ecs update-service --cluster registro-cloud-cluster --service registro-note-service --force-new-deployment